[global]
logfile                       = stdout
clienttimeout                 = 5000
fallbacktimeout               = 2500
waitforcards                  = 1

[dvbapi]
enabled                       = 1
au                            = 1
pmt_mode                      = 4
request_mode                  = 1
listen_port                   = 9000
serverip                      = 127.0.0.1
user                          = tvheadend
boxtype                       = pc

[webif]
httpport                      = 8888
httpallowed                   = 192.168.0.0-192.168.255.255,127.0.0.0-127.255.255.255,10.0.0.0-10.255.255.255
